# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Make venv
    before: python3 -m venv venv # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    init: venv/bin/pip install -r requirements.txt
  
  - name: migrate
    before: venv/bin/python manage.py migrate # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds