version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: myuser
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 1s
      timeout: 10s
      retries: 30
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: myuser
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  broker:
    image: redis
    volumes:
      - redis_data:/data
  worker:
    build: .
    command: celery -A GHCwebsite worker -l INFO
    environment:
      POSTGRES_DB: myuser
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    depends_on:
      - broker
    
volumes:
  database:
  redis_data:
