# Generated by Django 4.2.4 on 2023-08-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='ourvision',
            field=models.TextField(default='# this is a markdown title'),
            preserve_default=False,
        ),
    ]
