# Generated by Django 4.2.4 on 2023-08-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ourvisiontitle',
            field=models.CharField(default='Our Vision', max_length=500),
            preserve_default=False,
        ),
    ]
